base: 
  filePath: "../../税控电子9月.xlsx"
  tableName: "import_meter_two_01"
  skipRows: 1
  dataBaseName: "mysql"
databases: 
  mysql:
    userName: "root"
    password: "123456"
    ip: "127.0.0.1"
    port: 3306
    database: "go-zero-book"
